// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVIeuVTbuF7Lmv5A30aLIJzwENfHv4Kk',
    appId: '1:417035149751:web:1b77ea53dd61a45e690832',
    messagingSenderId: '417035149751',
    projectId: 'ai-assistant-94',
    authDomain: 'ai-assistant-94.firebaseapp.com',
    storageBucket: 'ai-assistant-94.firebasestorage.app',
    measurementId: 'G-QNQ1PEKGLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd00baKupmWHatVySgADTmGoOXkVlmg9U',
    appId: '1:417035149751:android:1802cbd8a191d7b1690832',
    messagingSenderId: '417035149751',
    projectId: 'ai-assistant-94',
    storageBucket: 'ai-assistant-94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXONhzsfKhz6Wi-Mh1c9BG_LcUa-wez4',
    appId: '1:417035149751:ios:2d34f0a65e0ae364690832',
    messagingSenderId: '417035149751',
    projectId: 'ai-assistant-94',
    storageBucket: 'ai-assistant-94.firebasestorage.app',
    iosBundleId: 'com.example.myAppGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project.appspot.com',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.myApp',
  );
}